/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_main_JRMathLib */

#ifndef _Included_org_main_JRMathLib
#define _Included_org_main_JRMathLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_main_JRMathLib
 * Method:    CMathExp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_main_JRMathLib_CMathExp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_main_JRMathLib
 * Method:    SumArrays
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_main_JRMathLib_SumArrays
  (JNIEnv *, jclass, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
